// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>STC08_ViewPanelInformation</b><br>
 * Generated     : <b>2015/11/20 3:38:08 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 8.1 x86 6.3 <br>
 * 
 * @since  November 20, 2015
 * @author John
 */
public abstract class STC08_ViewPanelInformationHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Back: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Back
	 */
	protected GuiTestObject button_back() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_back"));
	}
	/**
	 * Back: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Back
	 */
	protected GuiTestObject button_back(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_back"), anchor, flags);
	}
	
	/**
	 * LogInsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log In
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : loginButton
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_logInsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logInsubmit"));
	}
	/**
	 * LogInsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log In
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : loginButton
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_logInsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logInsubmit"), anchor, flags);
	}
	
	/**
	 * ISCControlSystem: with default state.
	 *		.title : ISC Control System
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8080/International_Science_Consortium/
	 */
	protected DocumentTestObject document_iscControlSystem() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_iscControlSystem"));
	}
	/**
	 * ISCControlSystem: with specific test context and state.
	 *		.title : ISC Control System
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8080/International_Science_Consortium/
	 */
	protected DocumentTestObject document_iscControlSystem(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_iscControlSystem"), anchor, flags);
	}
	
	/**
	 * DisplayMyPanels: with default state.
	 *		.text : Display My Panels
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanels.jsp
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link_displayMyPanels() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_displayMyPanels"));
	}
	/**
	 * DisplayMyPanels: with specific test context and state.
	 *		.text : Display My Panels
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanels.jsp
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link_displayMyPanels(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_displayMyPanels"), anchor, flags);
	}
	
	/**
	 * Logout: with default state.
	 *		.text : Logout
	 * 		.href : http://localhost:8080/International_Science_Consortium/logout
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	protected GuiTestObject link_logout() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logout"));
	}
	/**
	 * Logout: with specific test context and state.
	 *		.text : Logout
	 * 		.href : http://localhost:8080/International_Science_Consortium/logout
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	protected GuiTestObject link_logout(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logout"), anchor, flags);
	}
	
	/**
	 * ViewPanel: with default state.
	 *		.text : View Panel
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_viewPanel() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewPanel"));
	}
	/**
	 * ViewPanel: with specific test context and state.
	 *		.text : View Panel
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_viewPanel(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewPanel"), anchor, flags);
	}
	
	/**
	 * ViewPanel: with default state.
	 *		.text : View Panel
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_viewPanel2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewPanel2"));
	}
	/**
	 * ViewPanel: with specific test context and state.
	 *		.text : View Panel
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_viewPanel2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewPanel2"), anchor, flags);
	}
	
	/**
	 * ViewPanel: with default state.
	 *		.text : View Panel
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_viewPanel3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewPanel3"));
	}
	/**
	 * ViewPanel: with specific test context and state.
	 *		.text : View Panel
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_viewPanel3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewPanel3"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * HtmlTable_1: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_1() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_1"));
	}
	/**
	 * HtmlTable_1: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_1(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_1"), anchor, flags);
	}
	
	/**
	 * password: with default state.
	 *		.id : 
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_password() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_password"));
	}
	/**
	 * password: with specific test context and state.
	 *		.id : 
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_password(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_password"), anchor, flags);
	}
	
	/**
	 * username: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_username() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_username"));
	}
	/**
	 * username: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_username(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_username"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point htmlBrowser_standard object in the SUT.
	 */
	protected IFtVerificationPoint htmlBrowser_standardVP() 
	{
		return vp("htmlBrowser_standard");
	}
	protected IFtVerificationPoint htmlBrowser_standardVP(TestObject anchor)
	{
		return vp("htmlBrowser_standard", anchor);
	}
	
	/**
	 * Locate and return the verification point Rainy1ViewPanleInformationhtmlBrowser object in the SUT.
	 */
	protected IFtVerificationPoint Rainy1ViewPanleInformationhtmlBrowserVP() 
	{
		return vp("Rainy1ViewPanleInformationhtmlBrowser");
	}
	protected IFtVerificationPoint Rainy1ViewPanleInformationhtmlBrowserVP(TestObject anchor)
	{
		return vp("Rainy1ViewPanleInformationhtmlBrowser", anchor);
	}
	
	/**
	 * Locate and return the verification point Rainy1ViewPanleInformationHtmlTable object in the SUT.
	 */
	protected IFtVerificationPoint Rainy1ViewPanleInformationHtmlTableVP() 
	{
		return vp("Rainy1ViewPanleInformationHtmlTable");
	}
	protected IFtVerificationPoint Rainy1ViewPanleInformationHtmlTableVP(TestObject anchor)
	{
		return vp("Rainy1ViewPanleInformationHtmlTable", anchor);
	}
	
	/**
	 * Locate and return the verification point Rainy2ViewPanleInformationhtmlBrowser object in the SUT.
	 */
	protected IFtVerificationPoint Rainy2ViewPanleInformationhtmlBrowserVP() 
	{
		return vp("Rainy2ViewPanleInformationhtmlBrowser");
	}
	protected IFtVerificationPoint Rainy2ViewPanleInformationhtmlBrowserVP(TestObject anchor)
	{
		return vp("Rainy2ViewPanleInformationhtmlBrowser", anchor);
	}
	
	/**
	 * Locate and return the verification point Rainy2ViewPanleInformationHtmlTable object in the SUT.
	 */
	protected IFtVerificationPoint Rainy2ViewPanleInformationHtmlTableVP() 
	{
		return vp("Rainy2ViewPanleInformationHtmlTable");
	}
	protected IFtVerificationPoint Rainy2ViewPanleInformationHtmlTableVP(TestObject anchor)
	{
		return vp("Rainy2ViewPanleInformationHtmlTable", anchor);
	}
	
	/**
	 * Locate and return the verification point Rainy3ViewPanleInformationhtmlBrowser object in the SUT.
	 */
	protected IFtVerificationPoint Rainy3ViewPanleInformationhtmlBrowserVP() 
	{
		return vp("Rainy3ViewPanleInformationhtmlBrowser");
	}
	protected IFtVerificationPoint Rainy3ViewPanleInformationhtmlBrowserVP(TestObject anchor)
	{
		return vp("Rainy3ViewPanleInformationhtmlBrowser", anchor);
	}
	
	/**
	 * Locate and return the verification point Rainy3ViewPanleInformationHtmlTable1 object in the SUT.
	 */
	protected IFtVerificationPoint Rainy3ViewPanleInformationHtmlTable1VP() 
	{
		return vp("Rainy3ViewPanleInformationHtmlTable1");
	}
	protected IFtVerificationPoint Rainy3ViewPanleInformationHtmlTable1VP(TestObject anchor)
	{
		return vp("Rainy3ViewPanleInformationHtmlTable1", anchor);
	}
	
	/**
	 * Locate and return the verification point Sunny1ViewPanleInformationBrowser object in the SUT.
	 */
	protected IFtVerificationPoint Sunny1ViewPanleInformationBrowserVP() 
	{
		return vp("Sunny1ViewPanleInformationBrowser");
	}
	protected IFtVerificationPoint Sunny1ViewPanleInformationBrowserVP(TestObject anchor)
	{
		return vp("Sunny1ViewPanleInformationBrowser", anchor);
	}
	
	/**
	 * Locate and return the verification point Sunny1ViewPanleInformationHtmlTable object in the SUT.
	 */
	protected IFtVerificationPoint Sunny1ViewPanleInformationHtmlTableVP() 
	{
		return vp("Sunny1ViewPanleInformationHtmlTable");
	}
	protected IFtVerificationPoint Sunny1ViewPanleInformationHtmlTableVP(TestObject anchor)
	{
		return vp("Sunny1ViewPanleInformationHtmlTable", anchor);
	}
	
	/**
	 * Locate and return the verification point Sunny2ViewPanleInformationBrowser object in the SUT.
	 */
	protected IFtVerificationPoint Sunny2ViewPanleInformationBrowserVP() 
	{
		return vp("Sunny2ViewPanleInformationBrowser");
	}
	protected IFtVerificationPoint Sunny2ViewPanleInformationBrowserVP(TestObject anchor)
	{
		return vp("Sunny2ViewPanleInformationBrowser", anchor);
	}
	
	/**
	 * Locate and return the verification point Sunny2ViewPanleInformationHtmlTable object in the SUT.
	 */
	protected IFtVerificationPoint Sunny2ViewPanleInformationHtmlTableVP() 
	{
		return vp("Sunny2ViewPanleInformationHtmlTable");
	}
	protected IFtVerificationPoint Sunny2ViewPanleInformationHtmlTableVP(TestObject anchor)
	{
		return vp("Sunny2ViewPanleInformationHtmlTable", anchor);
	}
	
	/**
	 * Locate and return the verification point Sunny3ViewPanleInformationBrowser object in the SUT.
	 */
	protected IFtVerificationPoint Sunny3ViewPanleInformationBrowserVP() 
	{
		return vp("Sunny3ViewPanleInformationBrowser");
	}
	protected IFtVerificationPoint Sunny3ViewPanleInformationBrowserVP(TestObject anchor)
	{
		return vp("Sunny3ViewPanleInformationBrowser", anchor);
	}
	
	/**
	 * Locate and return the verification point Sunny3ViewPanleInformationHtmlTable object in the SUT.
	 */
	protected IFtVerificationPoint Sunny3ViewPanleInformationHtmlTableVP() 
	{
		return vp("Sunny3ViewPanleInformationHtmlTable");
	}
	protected IFtVerificationPoint Sunny3ViewPanleInformationHtmlTableVP(TestObject anchor)
	{
		return vp("Sunny3ViewPanleInformationHtmlTable", anchor);
	}
	
	

	protected STC08_ViewPanelInformationHelper()
	{
		setScriptName("STC08_ViewPanelInformation");
	}
	
}

