// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>STC08_ViewPanelInformation</b><br>
 * Generated     : <b>2015/11/18 11:15:06 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 8.1 x86 6.3 <br>
 * 
 * @since  November 18, 2015
 * @author John
 */
public abstract class STC08_ViewPanelInformationHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Back: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Back
	 */
	protected GuiTestObject button_back() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_back"));
	}
	/**
	 * Back: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Back
	 */
	protected GuiTestObject button_back(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_back"), anchor, flags);
	}
	
	/**
	 * LogInsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log In
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : loginButton
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_logInsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logInsubmit"));
	}
	/**
	 * LogInsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log In
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : loginButton
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_logInsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logInsubmit"), anchor, flags);
	}
	
	/**
	 * ISCControlSystem: with default state.
	 *		.title : ISC Control System
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8080/International_Science_Consortium/
	 */
	protected DocumentTestObject document_iscControlSystem() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_iscControlSystem"));
	}
	/**
	 * ISCControlSystem: with specific test context and state.
	 *		.title : ISC Control System
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8080/International_Science_Consortium/
	 */
	protected DocumentTestObject document_iscControlSystem(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_iscControlSystem"), anchor, flags);
	}
	
	/**
	 * ISCControlSystem: with default state.
	 *		.title : ISC Control System
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 */
	protected DocumentTestObject document_iscControlSystem2() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_iscControlSystem2"));
	}
	/**
	 * ISCControlSystem: with specific test context and state.
	 *		.title : ISC Control System
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 */
	protected DocumentTestObject document_iscControlSystem2(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_iscControlSystem2"), anchor, flags);
	}
	
	/**
	 * ISCControlSystem: with default state.
	 *		.title : ISC Control System
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8080/International_Science_Consortium/index.jsp
	 */
	protected DocumentTestObject document_iscControlSystem3() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_iscControlSystem3"));
	}
	/**
	 * ISCControlSystem: with specific test context and state.
	 *		.title : ISC Control System
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8080/International_Science_Consortium/index.jsp
	 */
	protected DocumentTestObject document_iscControlSystem3(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_iscControlSystem3"), anchor, flags);
	}
	
	/**
	 * DisplayMyPanels: with default state.
	 *		.text : Display My Panels
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanels.jsp
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link_displayMyPanels() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_displayMyPanels"));
	}
	/**
	 * DisplayMyPanels: with specific test context and state.
	 *		.text : Display My Panels
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanels.jsp
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link_displayMyPanels(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_displayMyPanels"), anchor, flags);
	}
	
	/**
	 * DisplayMyPanels: with default state.
	 *		.text : Display My Panels
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanels.jsp
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link_displayMyPanels2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_displayMyPanels2"));
	}
	/**
	 * DisplayMyPanels: with specific test context and state.
	 *		.text : Display My Panels
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanels.jsp
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link_displayMyPanels2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_displayMyPanels2"), anchor, flags);
	}
	
	/**
	 * Logout: with default state.
	 *		.text : Logout
	 * 		.href : http://localhost:8080/International_Science_Consortium/logout
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	protected GuiTestObject link_logout() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logout"));
	}
	/**
	 * Logout: with specific test context and state.
	 *		.text : Logout
	 * 		.href : http://localhost:8080/International_Science_Consortium/logout
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	protected GuiTestObject link_logout(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logout"), anchor, flags);
	}
	
	/**
	 * ViewPanel: with default state.
	 *		.text : View Panel
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_viewPanel() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewPanel"));
	}
	/**
	 * ViewPanel: with specific test context and state.
	 *		.text : View Panel
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_viewPanel(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewPanel"), anchor, flags);
	}
	
	/**
	 * ViewPanel: with default state.
	 *		.text : View Panel
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_viewPanel2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewPanel2"));
	}
	/**
	 * ViewPanel: with specific test context and state.
	 *		.text : View Panel
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_viewPanel2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewPanel2"), anchor, flags);
	}
	
	/**
	 * ViewPanel: with default state.
	 *		.text : View Panel
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_viewPanel3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewPanel3"));
	}
	/**
	 * ViewPanel: with specific test context and state.
	 *		.text : View Panel
	 * 		.href : http://localhost:8080/International_Science_Consortium/displayPanel.jsp?panelID= ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_viewPanel3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewPanel3"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_2"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_2"), anchor, flags);
	}
	
	/**
	 * password: with default state.
	 *		.id : 
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_password() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_password"));
	}
	/**
	 * password: with specific test context and state.
	 *		.id : 
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_password(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_password"), anchor, flags);
	}
	
	/**
	 * username: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_username() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_username"));
	}
	/**
	 * username: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_username(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_username"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_grid object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_gridVP() 
	{
		return vp("HtmlTable_0_grid");
	}
	protected IFtVerificationPoint HtmlTable_0_gridVP(TestObject anchor)
	{
		return vp("HtmlTable_0_grid", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_grid_2 object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_grid_2VP() 
	{
		return vp("HtmlTable_0_grid_2");
	}
	protected IFtVerificationPoint HtmlTable_0_grid_2VP(TestObject anchor)
	{
		return vp("HtmlTable_0_grid_2", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_grid_3 object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_grid_3VP() 
	{
		return vp("HtmlTable_0_grid_3");
	}
	protected IFtVerificationPoint HtmlTable_0_grid_3VP(TestObject anchor)
	{
		return vp("HtmlTable_0_grid_3", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_grid_4 object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_grid_4VP() 
	{
		return vp("HtmlTable_0_grid_4");
	}
	protected IFtVerificationPoint HtmlTable_0_grid_4VP(TestObject anchor)
	{
		return vp("HtmlTable_0_grid_4", anchor);
	}
	
	

	protected STC08_ViewPanelInformationHelper()
	{
		setScriptName("STC08_ViewPanelInformation");
	}
	
}

