// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>STC03_Logout</b><br>
 * Generated     : <b>2015/10/24 2:23:41 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 8.1 x86 6.3 <br>
 * 
 * @since  October 24, 2015
 * @author John
 */
public abstract class STC03_LogoutHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * LogInsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log In
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : loginButton
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_logInsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logInsubmit"));
	}
	/**
	 * LogInsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Log In
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : loginButton
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_logInsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_logInsubmit"), anchor, flags);
	}
	
	/**
	 * ISCControlSystem: with default state.
	 *		.title : ISC Control System
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8080/International_Science_Consortium/
	 */
	protected DocumentTestObject document_iscControlSystem() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_iscControlSystem"));
	}
	/**
	 * ISCControlSystem: with specific test context and state.
	 *		.title : ISC Control System
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8080/International_Science_Consortium/
	 */
	protected DocumentTestObject document_iscControlSystem(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_iscControlSystem"), anchor, flags);
	}
	
	/**
	 * ISCControlSystem: with default state.
	 *		.title : ISC Control System
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8080/International_Science_Consortium/index.jsp
	 */
	protected DocumentTestObject document_iscControlSystem2() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_iscControlSystem2"));
	}
	/**
	 * ISCControlSystem: with specific test context and state.
	 *		.title : ISC Control System
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8080/International_Science_Consortium/index.jsp
	 */
	protected DocumentTestObject document_iscControlSystem2(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_iscControlSystem2"), anchor, flags);
	}
	
	/**
	 * Administer: with default state.
	 *		.text : Administer
	 * 		.href : http://localhost:8080/International_Science_Consortium/messagePage?messageCode=Y ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_administer() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_administer"));
	}
	/**
	 * Administer: with specific test context and state.
	 *		.text : Administer
	 * 		.href : http://localhost:8080/International_Science_Consortium/messagePage?messageCode=Y ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_administer(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_administer"), anchor, flags);
	}
	
	/**
	 * EditPanelistProfile: with default state.
	 *		.text : Edit Panelist Profile
	 * 		.href : http://localhost:8080/International_Science_Consortium/messagePage?messageCode=Y ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_editPanelistProfile() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_editPanelistProfile"));
	}
	/**
	 * EditPanelistProfile: with specific test context and state.
	 *		.text : Edit Panelist Profile
	 * 		.href : http://localhost:8080/International_Science_Consortium/messagePage?messageCode=Y ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_editPanelistProfile(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_editPanelistProfile"), anchor, flags);
	}
	
	/**
	 * EditPanelistProfile: with default state.
	 *		.text : Edit Panelist Profile
	 * 		.id : 
	 * 		.href : http://localhost:8080/International_Science_Consortium/messagePage?messageCode=Y ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_editPanelistProfile2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_editPanelistProfile2"));
	}
	/**
	 * EditPanelistProfile: with specific test context and state.
	 *		.text : Edit Panelist Profile
	 * 		.id : 
	 * 		.href : http://localhost:8080/International_Science_Consortium/messagePage?messageCode=Y ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_editPanelistProfile2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_editPanelistProfile2"), anchor, flags);
	}
	
	/**
	 * Logout: with default state.
	 *		.text : Logout
	 * 		.id : 
	 * 		.href : http://localhost:8080/International_Science_Consortium/logout
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_logout() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logout"));
	}
	/**
	 * Logout: with specific test context and state.
	 *		.text : Logout
	 * 		.id : 
	 * 		.href : http://localhost:8080/International_Science_Consortium/logout
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_logout(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_logout"), anchor, flags);
	}
	
	/**
	 * SearchForPanelists: with default state.
	 *		.text : Search for Panelists
	 * 		.href : http://localhost:8080/International_Science_Consortium/searchPanelists.jsp
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_searchForPanelists() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_searchForPanelists"));
	}
	/**
	 * SearchForPanelists: with specific test context and state.
	 *		.text : Search for Panelists
	 * 		.href : http://localhost:8080/International_Science_Consortium/searchPanelists.jsp
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_searchForPanelists(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_searchForPanelists"), anchor, flags);
	}
	
	/**
	 * password: with default state.
	 *		.id : 
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_password() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_password"));
	}
	/**
	 * password: with specific test context and state.
	 *		.id : 
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_password(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_password"), anchor, flags);
	}
	
	/**
	 * username: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_username() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_username"));
	}
	/**
	 * username: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_username(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_username"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point FailedLogout1 object in the SUT.
	 */
	protected IFtVerificationPoint FailedLogout1VP() 
	{
		return vp("FailedLogout1");
	}
	protected IFtVerificationPoint FailedLogout1VP(TestObject anchor)
	{
		return vp("FailedLogout1", anchor);
	}
	
	/**
	 * Locate and return the verification point FailedLogout2 object in the SUT.
	 */
	protected IFtVerificationPoint FailedLogout2VP() 
	{
		return vp("FailedLogout2");
	}
	protected IFtVerificationPoint FailedLogout2VP(TestObject anchor)
	{
		return vp("FailedLogout2", anchor);
	}
	
	/**
	 * Locate and return the verification point FailedLogout3 object in the SUT.
	 */
	protected IFtVerificationPoint FailedLogout3VP() 
	{
		return vp("FailedLogout3");
	}
	protected IFtVerificationPoint FailedLogout3VP(TestObject anchor)
	{
		return vp("FailedLogout3", anchor);
	}
	
	/**
	 * Locate and return the verification point SuccessfulLogout object in the SUT.
	 */
	protected IFtVerificationPoint SuccessfulLogoutVP() 
	{
		return vp("SuccessfulLogout");
	}
	protected IFtVerificationPoint SuccessfulLogoutVP(TestObject anchor)
	{
		return vp("SuccessfulLogout", anchor);
	}
	
	

	protected STC03_LogoutHelper()
	{
		setScriptName("STC03_Logout");
	}
	
}

